### ISSUE TITLE
Problem: 1 Component - 2 Pages

### ISSUE THREAD

**Issue by jkblume** [iljabauer/agileselenium#33]
Found multiple matching syntax patterns: 
[<Page with TableUnderTest4> Assert column Many [StringParameter] in TableUnderTest4 is sorted [asc | desc], 
<Page with TableUnderTest4> Assert column Many [StringParameter] in TableUnderTest4 is sorted [asc | desc]]

**Comment by iljabauer** [comment]
Ich habe einen Fix committet, jedoch ist das Problem immer noch präsent, wegen dem return null | return false bug.
